### ISSUE TITLE
hyperrogue.html has a deprecated a version

### ISSUE THREAD

**Issue by nobrakal** [zenorogue/hyperrogue#1]
The version is 5.5 in the .html file.

Maybe it will be good to add add on it an autotools variable, to make the update automatically.

**Comment by zenorogue** [comment]
I have updated the version number in the html file. Still, the compilation instructions have to be updated.

**Comment by nobrakal** [comment]
Ok, thanks, I've also updated the version in the configure.ac file. I close the issue
