### ISSUE TITLE
Orb of Water has fun effects in the Caribbean

### ISSUE THREAD

**Issue by Quuxplusone** [zenorogue/hyperrogue#109]
I picked up an Orb of Water in the Living Fjord, got in a boat (which turned blue), and sailed to the Caribbean. I drove my boat into an island and started killing pirates. Driving onto a treasure causes it to vanish without a trace (not even a message about its sinking). I _think_ this is a bug but I'm not sure.

Driving onto a compass causes the compass to go inside the boat and move along with the boat, which is kind of cute because then you have a portable compass that always shows your distance from the edge of the nearest island. If you sail back outside of the island, then the compass number turns negative.

![](https://i.imgur.com/1rEdJlg.png)
![](https://i.imgur.com/t5UwyPo.png)
![](https://i.imgur.com/bVOhQpp.png)

If you're equidistant from several islands, the placement of the "X" is wonky.

![](https://i.imgur.com/VFRBiY0.png)

Then my boat sank in the Kraken Deeps, but the compass just stayed there in the middle of the ocean even after the boat sank.

![](https://i.imgur.com/S13Pl7C.png)

**Comment by zenorogue** [comment]
OK, so there were two bugs there: you could not collect items while you had a Compass on your boat, and a sunken Compass did not use underwater coloring. Both fixed. Thanks!
