### ISSUE TITLE
Missing R.raw.palace, R.raw.caribbean, R.raw.ocean, R.raw.ivory

### ISSUE THREAD

**Issue by relan** [zenorogue/hyperrogue#119]
Android build of v11.3l fails because of missing resources:

```
/home/vagrant/build/com.roguetemple.hyperroid/hyperroid/app/src/main/java/com/roguetemple/hyperroid/HyperRogue.java:528: error: cannot find symbol
  if(curland == 20) id = R.raw.palace; // Camelot
                              ^
  symbol:   variable palace
  location: class raw
/home/vagrant/build/com.roguetemple.hyperroid/hyperroid/app/src/main/java/com/roguetemple/hyperroid/HyperRogue.java:531: error: cannot find symbol
  if(curland == 23) id = R.raw.caribbean; // Caribbean
                              ^
  symbol:   variable caribbean
  location: class raw
/home/vagrant/build/com.roguetemple.hyperroid/hyperroid/app/src/main/java/com/roguetemple/hyperroid/HyperRogue.java:534: error: cannot find symbol
  if(curland == 26) id = R.raw.ocean; // Ocean
                              ^
  symbol:   variable ocean
  location: class raw
/home/vagrant/build/com.roguetemple.hyperroid/hyperroid/app/src/main/java/com/roguetemple/hyperroid/HyperRogue.java:538: error: cannot find symbol
  if(curland == 30) id = R.raw.ivory; // Ivory Tower
                              ^
  symbol:   variable ivory
  location: class raw
```

Full build log: https://f-droid.org/wiki/page/com.roguetemple.hyperroid/lastbuild_11309

**Comment by rpljwi** [comment]
I think the sound files are missing. Looking at (this)[https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.roguetemple.hyperroid.yml], which I'm assuming to be the "build recipe", I see that it should invoke `copy.sh`, which is supposed to copy the files to the `res` directory, yet the line supposedly copying music is commented: https://github.com/zenorogue/hyperrogue/blob/5654e632ce5157fe9532be892fd700c40aed59bd/hyperroid/copy.sh#L7

Could that be it?

**Comment by rpljwi** [comment]
Replacing the lines indicated above with
```
for x in ../music/hr3-*.ogg; do
    bn=${x##*/}
    cp $x app/src/main/res/raw/${bn#hr3-}
done

for x in ../music/hr-savino-*.ogg; do
    bn=${x##*/}
    cp $x app/src/main/res/raw/${bn#hr-savino-}
done
```
left me with missing files (and updated-to-highres old ones) in place.

**Comment by rpljwi** [comment]
So I'm guessing there either should be low-res versions of the new music, or all the hi-res music could just be packed into the app (which would probably grow in size considerably).

**Comment by zenorogue** [comment]
Thanks for the pull request! Yes, low-res versions of the new music was intended; I have been temporarily using the hi-res versions of the new files to compile the Android version, and then forgot about it.
