### ISSUE TITLE
Stepping on reptile floor doesn't reset it, when player is hasted

### ISSUE THREAD

**Issue by Quuxplusone** [zenorogue/hyperrogue#123]
Normally, in "Reptiles", when a reptile floor is flashing because it's about to come alive, the player can step on that floor to reset its counter.

When the Orb of Speed is active, stepping on the floor generally doesn't work to reset it. You have to step on it and then step again in the same place (i.e. remain still for another half-turn) in order to reset it.

This feels like a bug to me, in particular because "stepping on a thing" doesn't _generally_ require two turns when hasted; e.g., the hasted player can still set off a mine in the Minefield, collect a treasure, etc. in just one turn.

**Comment by zenorogue** [comment]
Fixed. Also fixed a similar situation with a quickly moving monster (Orb of Air, Eagle). Thanks!
