### ISSUE TITLE
Missing .ogg files for hyperroid

### ISSUE THREAD

**Issue by mwarning** [zenorogue/hyperrogue#126]
The `music/hr-savino-*.ogg` files need to be copied (and renamed) to `hyperroid/app/src/main/res/raw`.

**Comment by zenorogue** [comment]
I have recently merged a pull request which fixed this issue (by placing the low quality versions of the music there). Although there might be something else which prevents compiling the newer updates on Android...

**Comment by mwarning** [comment]
Ah, right. I checked out the latest release and did not notice that this issue has been fixed.
