### ISSUE TITLE
Entering Minefield from Plane of Eternal Motion, no way to find mine.

### ISSUE THREAD

**Issue by jeeger** [zenorogue/hyperrogue#14]
Hey! I don't know if this is really a bug, but:

When entering a minefield from the Plane of Eternal Motion, there might be one mine adjacent to your entry field.

Since there is no way to go back, it's impossible to get more information, and you basically have to pick a field to enter at random, leading to YAUD (yet another unavoidable death ☺).

Fix would be to always generate at least one "no adjacent mines" field on the minefield entrance.

**Comment by eryxcc** [comment]
This is avoidable (and thus intentional). When leaving the Land of Eternal Motion, you should first make sure that you will be able to continue. In particular, leaving to Minefield, Living Cave, or Alchemist Lab might be a bad idea.

**Comment by zenorogue** [comment]
This is avoidable (and thus intentional). When leaving the Land of Eternal Motion, you should first make sure that you will be able to continue. In particular, leaving to Minefield, Living Cave, or Alchemist Lab might be a bad idea.
