### ISSUE TITLE
Auto-rotation stopped working

### ISSUE THREAD

**Issue by panicbit** [zenorogue/hyperrogue#150]
### Steps to reproduce
Enter Ivory Tower.

### Observed behaviour
The camera does not rotate / behaves as usual when moving through "normal" lands.

### Expected behaviour
The camera should automatically rotate to orient itself with the gravity of Ivory Tower.

### Version
12.0a, 12.0b, Android (Playstore)

### Notes
- I do not know if this is isolated to Ivory Tower
- I was able to reproduce the issue with wiped settings

<img src="https://user-images.githubusercontent.com/628445/121208040-0deaf780-c87a-11eb-9c35-8df454d35df7.jpg" height="400" />

**Comment by panicbit** [comment]
The Windows version is not affected apparently.

**Comment by blargdag** [comment]
Also observed this on my Android device. Seems all gravity lands are affected. Only happens on version 12.0a, earlier versions were OK.

**Comment by blargdag** [comment]
Update: version 12.0b still has this problem on Android.

**Comment by zenorogue** [comment]
Should be fixed in 12.0v.
