### ISSUE TITLE
Halloween mini-game is broken

### ISSUE THREAD

**Issue by Quuxplusone** [zenorogue/hyperrogue#17]
I've got a rough patch [here](https://github.com/zenorogue/hyperrogue/compare/master...Quuxplusone:halloween), but I think there's still work to be done on "special modes"; hence why I'm posting an issue instead of a pull request.

I notice that hypersian rug mode also tries to `restartGame('e')` and `restartGame('E')`, both of which are unsupported. It might make sense for `restartGame` to check that its `switchWhat` argument is one of the expected chars.

**Comment by zenorogue** [comment]
I think this has been fixed in the meantime.
