### ISSUE TITLE
"Palace Quest" seems untranslatable?

### ISSUE THREAD

**Issue by blargdag** [zenorogue/hyperrogue#191]
Noticed that "Palace Quest" in the world overview is not being translated, so tried to add a translation line to `language-ru.cpp`. But after recompiling (from clean), the string is still not translated.  What gives?

**Comment by zenorogue** [comment]
Have you tried N(...) or with S(...)? 

"Palace Quest" is a (fake) land name, so you should translate it with N(...), not with S(...).

**Comment by blargdag** [comment]
Tried it with both `N(...)` and `S(...)`, neither works. "Palace Quest" appears untranslated in either case?

**Comment by zenorogue** [comment]
Worked for me. Maybe it is some specific instance of that? (I tested the one in World Overview)

**Comment by blargdag** [comment]
Oh?

**Comment by blargdag** [comment]
Oops closed by accident

**Comment by zenorogue** [comment]
Oh -- it seems that for some reason it does not work if the Polish translation is not available. I have been testing on the Polish translation, so that's why it was working for me.

(Pushed the Polish line, so it should work for you too now.)

**Comment by blargdag** [comment]
Cool, thanks! It works now.
