### ISSUE TITLE
computePathdist: OOB read from reachedfrom

### ISSUE THREAD

**Issue by jruderman** [zenorogue/hyperrogue#228]
In `computePathdist()`, sometimes the array `reachedfrom` is smaller than the array `pathq`, causing an OOB read past the end of `reachedfrom`:

```
for(; qb < isize(pathq); qb++) {
  cell *c = pathq[qb];
  int fd = reachedfrom[qb] + c->type/2;
```

I first noticed this with Address Sanitizer, which reports a "container-overflow". However, it's much faster to reproduce without ASan and instead sticking in:

```
if(qb >= isize(reachedfrom)) {
  printf("computePathdist: not enough reachedfrom! %d %d %s\n", isize(pathq), isize(reachedfrom), minf[param].name);
  addMessage("computePathdist: not enough reachedfrom");
  for (cell *cbuggy: pathq) {
    cbuggy->item = itWarning;
  }
  c->item = itTreat;
  cwt.at->item = itBuggy;
}
```

Observations:
* This happens many times per hour with autoplay, but I haven't figured out exactly what game situation triggers it.
* This happens most often when pathing for Tame Bomberbirds, but can happen for a variety of allies and enemies, and even when the pathdata constructor is called from `wandering()`.
* This happens more when pathing is restricted: Orb of the Warp, Orb of Lava, player surrounded by exploded mines, etc.
* It's actually more common for `reachedfrom` to be _larger_ than `pathq`, which doesn't cause an OOB read but probably means the angle is meaningless.

**Comment by zenorogue** [comment]
Thanks, hopefully it should be fixed now.
* `reachedfrom` larger than `pathq` happened because `reachedfrom` was used in `bfs` -- made it into two separate variables, `path_reachedfrom` and `bfs_reachedfrom`.
* `movehex_rest` could call `onpath` without previously creating a `pathdata`, causing `pathq` to be non-empty on the next call to `computePathdist`.

**Comment by jruderman** [comment]
After 5dbda4c896b0a8fd646589c291005190f775790d, I get an error in system.cpp:
```
system.cpp:1696:13: error: use of undeclared identifier 'reachedfrom'
  gd->store(reachedfrom);
```

**Comment by zenorogue** [comment]
Removed this line myself, forgot to push. Should be fixed now.
