### ISSUE TITLE
beastAttack/determinePush crash (null cell deref)

### ISSUE THREAD

**Issue by jruderman** [zenorogue/hyperrogue#234]
I've seen two autoplay crashes within beastAttack callbacks. [One crash](https://github.com/zenorogue/hyperrogue/files/6806110/beastattack.crash.push.monst.txt) was in the `passable` call:

`auto mi = determinePush(bull, subdir, [c2] (movei mi) { return passable(mi.t, c2, P_BLOW) && !isPlayerOn(mi.t); });`

and [the other crash](https://github.com/zenorogue/hyperrogue/files/6806111/beastattack.crash.thumper.txt) was in the `canPushThumperOn` call:

`auto mi = determinePush(bull, subdir, [c] (movei mi) { return canPushThumperOn(mi, c); });`

Is it possible that the Raging Bull is trying to push things onto distant-from-player cells that haven't been generated yet?

**Comment by jruderman** [comment]
Caught it in lldb: [debug log](https://github.com/zenorogue/hyperrogue/files/6820181/beastattack.extra.txt)

**Comment by zenorogue** [comment]
Yeah, it appears that mi was constructed with the `movei` constructor which constructed a move in a direction that was not generated yet.

Changed the `movei` constructor to call `cmove` instead of `move` -- hopefully this should fix this issue.

**Comment by jruderman** [comment]
I ran autoplay for a few hours and didn't see any crashes, so I think that fixed it :)
