### ISSUE TITLE
Ally-protection warning activates the Flash spell

### ISSUE THREAD

**Issue by jruderman** [zenorogue/hyperrogue#247]
1. Have Thorns and Flash
2. Have an adjacent Golem
3. Attempt to move in such a way that Thorns would kill the Golem

Result: hit warning appears _and_ Flash spell activates

Expected: hit warning should appear without activating Flash spell

**Example 1**

<img width="361" alt="image" src="https://user-images.githubusercontent.com/692547/126090021-ca44af2a-463d-46c4-987c-73b386b2defc.png">

Attempting to move onto the boat triggers a hit warning. It seems that `pcmove::movepcto` interprets the hit warning as an illegal move and activates the Flash spell as a result.

**Example 2**

<img width="372" alt="image" src="https://user-images.githubusercontent.com/692547/126090685-4c9a02d6-f836-4dc0-9453-eb6a93168c4b.png">

With the Yeti present, moving onto the boat is an illegal move (at least without hardcore). In this case, it might be better to not show the warning about Thorns and simply activate the Flash spell.

**Comment by zenorogue** [comment]
Warnings should no longer evoke Flash and Lightning.

(In Example 2 it still does show a warning -- but I think it is fine.)
