### ISSUE TITLE
Grabbing an Orb of Friendship with Orb of Space spawns bomberbird under player

### ISSUE THREAD

**Issue by blargdag** [zenorogue/hyperrogue#260]
Not sure if this is deliberate -- but if you grab an orb of friendship remotely using the orb of space, the bomberbird will spawn in the same cell, underneath the player. Looks very weird.  I'd expect it should spawn on an adjacent cell if one is available instead, since picking up the orb under normal circumstances spawns the bird in an adjacent cell.

**Comment by zenorogue** [comment]
Usually orb creatures spawn specifically in the cell you moved from.

So while it looks weird, I think it makes sense for the Orb of Space -- it also spawns in the cell you moved from, you just did not move yet. (It could also spawn in its original cell, but then what about OSM?)

There were still some other special cases:
* you jumped with Orb of the Frog or similar -> made it also spawn in the cell you moved from
* the item moved to you (Windy Plains, Free Fall, Orb of Magnetism, Orb of Water in Living Fjord)  -> made it spawn in the cell it moved from
