### ISSUE TITLE
"Too fatigued" to enter Ivory Tower in Euclidean

### ISSUE THREAD

**Issue by jruderman** [zenorogue/hyperrogue#265]
`./hyper -geo euclid -W Cross -W2 Ivory`

Trying to enter the Ivory Tower results in the message "You are too fatigued!".

Notes:

* `fatigue_cost` calls `gravityLevelDiff`.
* In this Euclidean geometry, all Ivory Tower cells have `gravityLevel` return 65535.

Related:

* Sir Light LJIJ [reports](https://discord.com/channels/540092734300618753/550649218885353472/863961132296568842) that the same can happen in hyperbolic geometry, when moving between Farlands and Yendorian Forest.
* DivisionByZero [reports](https://discord.com/channels/540092734300618753/550649218885353472/858218950974504980) that the same can happen after using the map editor to create a lone Dungeon cell.

**Comment by zenorogue** [comment]
Thanks for the report, should be fixed.
