### ISSUE TITLE
Freeze with Free Fall in Euclidean

### ISSUE THREAD

**Issue by jruderman** [zenorogue/hyperrogue#268]
1. `./hyper -f0 -geo euclid -W Crossroads -W2 "Free Fall"`
2. Make any move (including staying still)

About 70% of the time, this results in a freeze within `westwall::move()`.

**Comment by zenorogue** [comment]
Equidistant-based lands should not appear in Euclidean except in the single land mode.

Somehow they (as well as Camelot) still appeared in the Overview (not sure whether they would generate), so made them not appear there.

So while you can still do set these command line options, that situation should not happen (neither in multi-land, nor in single-land where Free Fall and Ivory Tower should work fine). Also made westwall detect infinite loops just in case.
