### ISSUE TITLE
Caribbean is disabled in standard run with hyperbolic geometry

### ISSUE THREAD

**Issue by Maugrift** [zenorogue/hyperrogue#297]
The Caribbean is currently not spawning in a standard run using the default hyperbolic geometry settings. I've tested this by collecting 30 treasures and boating around the ocean for several minutes, as well as looking into the world overview screen. The land overview screen indicates that it's only available in single land mode, but the selection screen in single land mode shows it as locked.

I use the `hyperrogue-git` package from the Arch Linux User Repository (AUR), which currently lists the version as `12.0f.r172.gc7ccb0b6-1`. I suspect this bug may have been caused by ae03bd52724842204efae9a5848a41faa8402319 just by looking at the commit message and the diff.

### Screenshots

World overview screen:
![image](https://user-images.githubusercontent.com/20198534/134821655-7048f552-3380-476f-b998-1aecc93da0af.png)

Land info (accessed from the world overview screen):
![image](https://user-images.githubusercontent.com/20198534/134821660-520f00c3-22a9-44e9-82eb-28b7bd86083b.png)

Single land mode - land selection:
![image](https://user-images.githubusercontent.com/20198534/134821664-b95cfb50-6dea-4cd1-8468-07b0aa715ecf.png)

**Comment by zenorogue** [comment]
Seems the Caribbean was to be disabled outside of single-land mode in Euclidean (but forgot to check about Euclidean). Thanks!
