### ISSUE TITLE
Can't compile in mingw-w64

### ISSUE THREAD

**Issue by Danfun64** [zenorogue/hyperrogue#30]
I wanted to compile the latest build of hyperrogue on windows. After making platform specific adjustments (C_CHECK_LIB([GL]...) to C_CHECK_LIB([opengl32]...) and C_CHECK_LIB([GLEW]...) to C_CHECK_LIB([glew32]...) ) I was able to get it to compile, but then I got the following error:

`In file included from init.cpp:358:0,
                 from hyper.cpp:34:
mapeditor.cpp: In function 'void mapeditor::drawFileDialog()':
mapeditor.cpp:595:22: error: 'struct dirent' has no member named 'd_type'; did you mean 'd_name'?
         else if(dir->d_type & DT_DIR)
                      ^~~~~~
                      d_name
mapeditor.cpp:595:31: error: 'DT_DIR' was not declared in this scope
         else if(dir->d_type & DT_DIR)
                               ^~~~~~
mapeditor.cpp:595:31: note: suggested alternative: '_WDIR'
         else if(dir->d_type & DT_DIR)
                               ^~~~~~
                               _WDIR
make[1]: *** [Makefile:522: hyperrogue-hyper.o] Error 1
make[1]: Leaving directory '/c/users/danfu/documents/hyperrogue'
make: *** [Makefile:378: all] Error 2
`

Can someone make a fix for this? Also a fix for configure.ac that works on all platforms?

**Comment by Quuxplusone** [comment]
It looks like this *ought* to work (git grep for `direntx.h`). Do you have `WINDOWS` and/or `ISWINDOWS` defined?
Are you using `Makefile.mgw`? What happens if you add `-DWINDOWS` to all the `g++` command lines in that makefile?

**Comment by Danfun64** [comment]
I used Makefile.mgw and got the same result. Honestly, I'd prefer being able to make a fresh makefile from autogen.sh, as premade make files can and most likely will become outdated.

**Comment by Quuxplusone** [comment]
You added `-DWINDOWS` and still got the same error? What about adding `-DISWINDOWS`?

> I'd prefer being able to make a fresh makefile from autogen.sh, as premade make files can and most likely will become outdated

Funny, I prefer pre-made makefiles for exactly the same reason! As you've observed, `autogen.sh` has bit-rotted and you are incapable of fixing it by hand, whereas I fixed the bit-rot in `Makefile.mac` and got it up and running in about five minutes. And my comments here are intended to suggest that you could fix `Makefile.mgw` in five minutes, too (by adding `-DWINDOWS` to the compiler command lines), although without a Windows machine to test on, I can't know for sure.

**Comment by Danfun64** [comment]
I'm incapable of fixing it by hand because i'm not a real coder.

**Comment by Danfun64** [comment]
@Quuxplusone did you notice my last comment? You might have missed the edit.

**Comment by Quuxplusone** [comment]
@Danfun64: I did miss the edit; thanks! It definitely looks like you need to add `-std=c++11` to the compiler command line in the Makefile — I don't understand how that first error is happening, but I hope that `-std=c++11` will magically fix it. (HyperRogue definitely uses C++11.)
For the lack of `_A_VOLID`, I don't know. The intention is clearly that `_A_VOLID` should be defined by `<io.h>` on Windows, but [this MSDN page](https://msdn.microsoft.com/en-us/library/aa272705(v=vs.60).aspx) suggests that this is no longer true, if indeed it ever was. As a quick fix, you could try adding `-D_A_VOLID=8` to the compiler command line.

    g++ -std=c++11 -mwindows hyper.cpp hyper.res -o hyper.exe -lSDL -lSDL_mixer -lopengl32 -lSDL_ttf -lSDL_gfx -lglew32 -O3 -DWINDOWS -D_A_VOLID=8

**Comment by Danfun64** [comment]
http://paste.debian.net/1010793/

**Comment by Quuxplusone** [comment]
@Danfun64: Well, this seems absolutely bonkers that MinGW would be doing this, but my working hypothesis now is that "`R10`" is somehow being treated as a magic keyword by your compiler — presumably related to the fact that `%r10` is the name of a register on x86-64. Notice that the compiler is happy with the definition of macro `U10` on the line *before* the error, even though it's essentially identical to the offending line.

So you could try applying the patch linked above and see if *that* helps. I just mechanically added a bunch of underscores to make `R10` into `R_10` and so on.

    git remote add quuxplusone https://github.com/Quuxplusone/hyperrogue.git
    git fetch quuxplusone no-r10
    git cherry-pick quuxplusone/no-r10
    g++ -std=c++11 -mwindows hyper.cpp hyper.res -o hyper.exe -lSDL -lSDL_mixer -lopengl32 -lSDL_ttf -lSDL_gfx -lglew32 -O3 -DWINDOWS -D_A_VOLID=8

**Comment by Danfun64** [comment]
http://paste.debian.net/1010801/

**Comment by Quuxplusone** [comment]
Wow, I think we're about to do it! This last linker error is already described in Makefile.mgw:

    # you can also include savepng.c and remove -DNOPNG

So add `-DNOPNG` to the compiler command line. (If that fails, you could try adding `savepng.c` to the command line; or adding `-lSDL_SavePNG`.)

**Comment by Danfun64** [comment]
Um, where exactly is savepng.c supposed to go in the command line?

**Comment by Danfun64** [comment]
Just to let you know, I still get issues even with -DNOPNG inserted back in.

**Comment by Quuxplusone** [comment]
savepng.c can go anywhere on the command line: try right after the .cpp
file.
What's the -DNOPNG error message?

**Comment by Danfun64** [comment]
http://paste.debian.net/1010908/

**Comment by Quuxplusone** [comment]
That'll teach me to trust the Makefile that we knew was bit-rotted! 😛 

```
$ git grep -l NOPNG
Makefile.mgw
$ git grep -l CAP_PNG
basegraph.cpp
hyper.h
hyperweb.cpp
init.cpp
```

The correct thing to put on the compiler command line is `-DCAP_PNG=0`, not `-DNOPNG`. This identifier apparently changed back in July 2017 (8cb8e2a3).

    g++ -std=c++11 -mwindows hyper.cpp hyper.res -o hyper.exe -lSDL -lSDL_mixer -lopengl32 -lSDL_ttf -lSDL_gfx -lglew32 -O3 -DWINDOWS -D_A_VOLID=8 -DCAP_PNG=0

**Comment by Danfun64** [comment]
http://paste.debian.net/1011199/

It compiles! IT COMPILES! EEEEEEEE!

I'm pretty sure that Vista or newer is required for anything compiled in MSYS2/MinGW-W64 to run. Here is a list of all the (64-bit) dll's from MSYS2 the game wants: http://paste.debian.net/1011201/ . I'm not sure what the required dlls are for a 32-bit compile atm...

**Comment by Danfun64** [comment]
New bug. Sound only works when the game runs from the msys2 terminal.

**Comment by Quuxplusone** [comment]
Awesome!  Glad I could help with the Makefile at least.  Sound is way above my pay grade, though. Can I recommend that you open a fresh issue for the sound not working?

Meanwhile, I'll post a pull request with the changes we identified in this issue. I don't know what the actual project owner's policy about accepting pull requests is. They pulled one of mine a long time ago, but I've had a couple others sitting open for months with no comments.

**Comment by Danfun64** [comment]
Just replace mingw64 with mingw32 on that list i posted and you'll have the dll's needed for a 32-bit build.

**Comment by Quuxplusone** [comment]
> edit: I'm not sure you should post that pull request until sound is working without using msys2's terminal.

(A), too late. ;)
(B), I personally will be no use to you on the audio issue, sorry. Therefore I figure it's better for me to pull-request what little I can and get out cleanly. That's also why I suggest making a fresh new issue for the audio thing, with an appropriate title and whatever mass of information you can collect about the problem, and none of our previous 21 comments to distract whoever *might* be inclined to figure it out. (Of course I also recommend describing in that PR the exact way by which you built the game, in terms of `git pull quuxplusone mingw` and so on.)

**Comment by Danfun64** [comment]
In case you couldn't tell, I figured out the problem with the sound. Turns out I forgot about some dlls.
