### ISSUE TITLE
Android stability regression

### ISSUE THREAD

**Issue by blargdag** [zenorogue/hyperrogue#311]
In the previous Android update (12.0b), when Hyperrogue is backgrounded it would add an "game in progress" notification to the system, which prevents Android from killing the game in progress. The latest update (12.0u) no longer has this, which means every time you switch away to from the app (e.g., incoming phone call, check notifications) there's a risk that the OS will just unceremoniously kill the current game.  This effectively makes the game unplayable, because e.g., incoming phone calls are not under the user's control, but can randomly kill hours of gameplay forcing you to restart from zero.

Please reinstate the in-progress notification, as otherwise the game is basically unplayable on Android.

**Comment by zenorogue** [comment]
Seems to work for me. This feature is enabled only if you have >= 10 treasure or >= 50 kills, maybe you are testing in a very early game?

**Comment by blargdag** [comment]
On Sat, Jul 16, 2022 at 02:15:18AM -0700, Zeno Rogue wrote:
>    Seems to work for me. This feature is enabled only if you have >= 10
>    treasure or >= 50 kills, maybe you are testing in a very early game?
[...]

Tested again, it seems the problem is actually caused by hyperrogue
crashing upon switching away, and sometimes when dying. Do you know if
there's some way of getting at the error message? I don't see anything
obvious but at least once the OS prompted me to clear the cache because
the app keeps crashing, so there's definitely something going on.

This is definite happening with >=10 treasure.

**Comment by zenorogue** [comment]
Thanks for the report!! Again, some changes to Android have made HyperRogue crash... hopefully should be fixed in 12.0v.

**Comment by zenorogue** [comment]
@blargdag could you please confirm if it works now?

**Comment by zenorogue** [comment]
Seems HyperRogue Gold 12.0v was not uploaded for some reason (but standard HyperRogue 12.0v should be there).

I have also uploaded 12.0v to https://zenorogue.itch.io/hyperrogue

**Comment by blargdag** [comment]
Looks like 12.0v Gold just hit Play Store. Seems to work now, thanks!!
