### ISSUE TITLE
12u won't launch from launcher

### ISSUE THREAD

**Issue by licaon-kter** [zenorogue/hyperrogue#312]
12.0u F-Droid Android 11

Saw something like this elsewhere: https://github.com/idiomReplaceX/IdiomReplaceX-app/commit/968fd086e6d957519a71b8247142a286a842d02c

Ref: https://github.com/Neamar/KISS/issues/1946

**Comment by TheLastProject** [comment]
Should already be fixed in https://github.com/zenorogue/hyperrogue/commit/436cc15dbafa266c3431db27caafc5b848b98a57

**Comment by genpfault** [comment]
[App Manager](https://github.com/MuntashirAkon/AppManager) can launch the `.HyperRogue` activity directly via the "Activities" tab.

**Comment by Iizuki** [comment]
KISS refuses to launch this for me as well. Tried Nova, which fails as well but gives "Permission denied" as the reason.

**Comment by licaon-kter** [comment]
future 13a will fix thiis: https://gitlab.com/fdroid/fdroiddata/-/commit/dd09db4ccd76c83405160110fcd0584c1688df76
