### ISSUE TITLE
Could you add your app into F-Droid?

### ISSUE THREAD

**Issue by KOLANICH** [zenorogue/hyperrogue#33]

**Comment by picsi** [comment]
Do you think it could be done, @rudloff?

**Comment by Rudloff** [comment]
Now that https://github.com/zenorogue/hyperrogue/issues/35 is closed, it should be possible to package the app on [F-Droid](https://f-droid.org/) (if @zenorogue agrees, of course).

**Comment by zenorogue** [comment]
Sure!

**Comment by Rudloff** [comment]
Great! Do you plan on publishing a new release that would include fixes from #35?

**Comment by zenorogue** [comment]
Pushed fixes from #35, and a release tag added.

**Comment by licaon-kter** [comment]
@zenorogue Any thoughts: https://f-droid.org/wiki/page/com.roguetemple.hyperroid/lastbuild_10505 ?

**Comment by zenorogue** [comment]
It appears something is wrong with the file `language-data.cpp` (as if it did not exist, but I do not see the compiler complain about that). This file is created by `langen`, so compile and run `langen.cpp` to fix it.

**Comment by KOLANICH** [comment]
Why not to use gettext or Qt Linguist?

**Comment by zenorogue** [comment]
Every game/software I have used had ugly Polish translations, so it appeared that I have to write my own translation engine if I want a beautiful Polish translation. More details here: https://github.com/zenorogue/hyperrogue/issues/3
