### ISSUE TITLE
Crash while playing in Shmup Mode

### ISSUE THREAD

**Issue by GalaxyLJGD** [zenorogue/hyperrogue#36]
Good day, the game crashes when I throw the sword and it hits an enemy in Shmup mode, also, to enter the Shmup mode I must go to the menu of special game modes, because when selecting it in the menu that appears at the beginning of the game, starts in normal mode and not in Shmup.

Here is the information about my computer:

System: Kernel: 4.14.44-1-MANJARO x86_64, bits: 64 Desktop: Xfce 4.12.4, Distro: Manjaro Linux 17.1.10 Hakoila.
Graphics: Card-1: Intel Atom Processor D4xx/D5xx/N4xx/N5xx Integrated Graphics, driver: i915, v: kernel, Display: x11, server: X.Org 1.19.6, driver: intel, resolution: 1024x600~60Hz, OpenGL: renderer: Mesa DRI Intel Pineview M, v: 1.4 Mesa 18.0.4
HyperRogue version: 10.0g

[Here is the GDB output](https://ghostbin.com/paste/pxtsk).

[Here is "hyperrogure-debug.txt" content](https://ghostbin.com/paste/5vgmk).

[And here is my configuration](https://ghostbin.com/paste/8v2uf).

PD: The crash happens even if I use OpenGL.

I hope that it will be useful, sorry for my bad english and thank you in advance.

**Comment by zenorogue** [comment]
Could not reproduce in 10.0g. Does this problem still exist in version 10.4b? If yes, the GDB output should be much more useful if HyperRogue is compiled with the debugging symbols ("-g" compiler option). Thanks!
