### ISSUE TITLE
Mutant Ivy does not spawn in clearing in Hyperbolic Goldberg Polyhedra

### ISSUE THREAD

**Issue by ChristopherKing42** [zenorogue/hyperrogue#37]
I am using Hyperrogue 10.4b. When doing hyperbolic GP(2,0) and other nonstandard Hyperbolic Goldberg Polyhedra, the mutant ivy does not spawn in the clearing.

**Comment by zenorogue** [comment]
Well, not all lands are fully implemented in all geometries. Lands with problems are marked with:

* a "(X)" symbol in the list of lands ("does not work at all")
* a message when you start the game ("Not implemented" in this case)

For 10.4 I have added (X) symbols also in the list of geometries when you have already selected a land, and a status message in the experiments menu.

**Comment by ChristopherKing42** [comment]
Ah okay.
