### ISSUE TITLE
How to escape this?

### ISSUE THREAD

**Issue by TLINDEN** [zenorogue/hyperrogue#388]
I am rather new to the game. Every now and then I end up in such a situation:

[
![Screenshot_20241009-231239](https://github.com/user-attachments/assets/87207ef9-36ab-4b2b-9cd7-0cc08fda2ff4)
](url)

Now I can't move anywhere, the only thing possible is to abort.

Is there any other way?

**Comment by zenorogue** [comment]
From what I can tell from your screenshot:
- You are playing in the Orb Strategy Mode
- For getting 10 Ice Diamonds, you have received an Orb of Winter and an Orb of Flash
- You have received 2 more orbs for collecting more ice diamonds
- You have just activated an Orb of Winter (hence the orb list shows 3 unused orbs, 1 dead orb, and a fully-charged Orb of Winter)

You should click the orb icon (with number "3"), and choose the Orb of Flash from the screen shown. Then click one of the yetis. This Orb will explode, letting you escape the situation.

Is this correct?

**Comment by TLINDEN** [comment]
It worked, wow! How cool is that?!

Thanks a lot, @zenorogue 😁👍
