### ISSUE TITLE
Needs `using std::abs`

### ISSUE THREAD

**Issue by Quuxplusone** [zenorogue/hyperrogue#39]
Your `using ...` patch actually introduced a problem, says Clang. All your unqualified `abs`es are now finding `int abs(int)` from `stdlib.h` instead of `double std::abs(double)`. Easy one-line fix to add `using std::abs;` in `hyper.h`.

```
./rug.cpp:647:18: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
  bool nonzero = abs(t-rd) > err_zero_current;
                 ^
./rug.cpp:647:18: note: use function 'std::abs' instead
  bool nonzero = abs(t-rd) > err_zero_current;
                 ^~~
                 std::abs
```

**Comment by zenorogue** [comment]
Added `using std::abs` and likewise other functions from <cmath>. Thanks!
