### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [zenorogue/hyperrogue#397]
https://gitlab.com/fdroid/fdroiddata/-/jobs/8709591922

I also tried some other commits but all of them failed with different errors. Could you please take a look? Thanks!

**Comment by zenorogue** [comment]
This was about a recently introduced keyboard feature not being disabled on Android, should be fixed now. Hopefully there is no more problems. Thanks for the report!

**Comment by linsui** [comment]
Thanks!
