### ISSUE TITLE
SEGFAULT when I collect gem in Palace

### ISSUE THREAD

**Issue by Knowledge-soda** [zenorogue/hyperrogue#57]
`uname -a` returns
`Linux 4.9.0-7-amd64 #1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux`
I've tried several times and every time I collect gem in Palace I get SEGFAULT (there is number 1625 before it, but that might be process id).

**Comment by zenorogue** [comment]
This bug has been introduced in a recent update (10.4n), and already fixed (in 10.4o). Or does it still happen in the newest version on GitHub?

**Comment by Knowledge-soda** [comment]
I had version 10.4m, now when I update to new version 10.4o it doesn't happen anymore so issue is fixed. Thanks.
