### ISSUE TITLE
Incorrect use of isnumber()

### ISSUE THREAD

**Issue by AMDmi3** [zenorogue/hyperrogue#61]
10.4t fails to build:

```
In file included from hyper.cpp:18:
In file included from ./init.cpp:4:
In file included from ./compileunits.h:33:
./archimedean.cpp:777:43: error: expected expression
      at++; int a = read_number(); while(!isnumber() && !among(peek(), '(', '[', ')',']', 0)) at++;
                                          ^
/usr/include/ctype.h:129:34: note: expanded from macro 'isnumber'
#define isnumber(c)     __sbistype((c), _CTYPE_D|_CTYPE_N)
                                     ^
```

obviously isnumber requires an argument.

**Comment by Quuxplusone** [comment]
Less obviously: `isnumber` is a (non-standard) macro on some systems! Actually technically C and C++ "reserve" all identifiers matching the regex `is[a-z].*`, so technically even defining the lambda `isnumber` caused undefined behavior. 😛 The simplest fix is to replace `isnumber` with `is_number`.

**Comment by AMDmi3** [comment]
Oh, I've missed that it's custom lambda in hyperrogue code. I think I can make a patch to rename it.
