### ISSUE TITLE
Orb of Recall + Orb of Safety bug

### ISSUE THREAD

**Issue by michael-heerdegen** [zenorogue/hyperrogue#78]
Hi,

I only tried this in shmup mode.  AFAIK this bug has existed as long as recall had been introduced.  I already mentioned it in a private conversation, but now I checked that it is still present in - what do I have now - 11.1d I think.

Get an Orb of Recall.  Before it runs out, take an orb of safety.  Everything is as expected so far.  But when now the orb of recall kicks in, your are not taken back (I guess your old map had been thrown away anyway), but instead the view starts to scroll away from your character until only blackness is visible. And a button appears saying "Find the player" (in the desktop version!).  It is not helpful (does nothing).  Only killing the game helps.

Does the game know what it should do in this situation? (As said, I didn't try normal mode, but I guess saving after using safety would complicate things further)  If not, how about just deactivating any pending recall when orb of safety is used?

TIA, Michael (yes, that guy that doesn't finish the German translation...)

**Comment by zenorogue** [comment]
Fixed in 11.1f.

**Comment by michael-heerdegen** [comment]
Zeno Rogue <notifications@github.com> writes:

> Fixed in 11.1f.

Thanks for fixing!
