### ISSUE TITLE
shmup: orb of water: can't collect other orbs

### ISSUE THREAD

**Issue by michael-heerdegen** [zenorogue/hyperrogue#79]
Hi,

when I take an orb of water while playing in shmup-mode, I can't pick up any other orb.  When I drive to any orb with my boat, the orb is removed from the map as if I had picked it up, but I don't get its effect, and it's not shown in the list of active orbs.  When orb of water times out, the problem is gone.  TIA, Michael.

**Comment by zenorogue** [comment]
Fixed in 11.1f.

**Comment by michael-heerdegen** [comment]
Zeno Rogue <notifications@github.com> writes:

> Fixed in 11.1f.

Thanks!
