### ISSUE TITLE
Path to music is broken

### ISSUE THREAD

**Issue by AMDmi3** [zenorogue/hyperrogue#8]
From #7:

Hmm, actually the target [which replaces strings in hyperrogue-music.txt] seems to be useless as it doesn't replace anything in the file (there are no ```music``` substings). Maybe that's that's the cause 8.3j is broken, as while it installs music into ${datadir}/music, it searches for it in ${datadir}:

```
% hyperrogue
HyperRogue by Zeno Rogue <zeno@attnam.com>, version 8.3j
released under GNU General Public License version 2 and thus
comes with absolutely no warranty; see COPYING for details
Mix_LoadMUS: Couldn't open '/usr/local/share/hyperrogue/hr3-icyland.ogg'
% ls /usr/local/share/hyperrogue/**/hr3-icyland.ogg 
/usr/local/share/hyperrogue/music/hr3-icyland.ogg
```

**Comment by nobrakal** [comment]
The problem is normally now corrected with commit 27c1b678c2276b4a45897cb86cf71bfabed27a9c

Thank you :)
