### ISSUE TITLE
New music files not installed

### ISSUE THREAD

**Issue by reinerh** [zenorogue/hyperrogue#84]
The new music files (hr-savino-caribbean.mp3, hr-savino-ivory.mp3, hr-savino-ocean.mp3, hr-savino-palace.mp3) are currently not installed.
They probably need to be added to dist_music_DATA in Makefile.am.

And in hyperrogue-music.txt the new tracks are referenced as .ogg files, not as .mp3.
So either the paths need to be adjusted (if hyperrogue can play mp3 files), or the files need to be re-encoded to .ogg.

**Comment by zenorogue** [comment]
Thanks! Should be fixed. The files are originally ogg, I must have added mp3 files by mistake.
