### ISSUE TITLE
Missing tag for 9.4c

### ISSUE THREAD

**Issue by AMDmi3** [zenorogue/hyperrogue#9]
Source code and tag for version 9.4c are missing

**Comment by AMDmi3** [comment]
Also for 9.4n

**Comment by nobrakal** [comment]
Almost all commits are corresponding to a version, so I think that this is only needed when a major update is published...

**Comment by AMDmi3** [comment]
Not sure what you mean by commits corresponding to a version. Tags are needed for a packaging, so the official release which is considered stable can be referenced, and to simplify the packaging by getting source by ihtub tag instead of commit number.

**Comment by AMDmi3** [comment]
Tag for 10.0g is missing too

**Comment by zenorogue** [comment]
Added the tags for 10.0o.

**Comment by zenorogue** [comment]
Added the tags for 10.4b.
