### ISSUE TITLE
Inconsistent git tags

### ISSUE THREAD

**Issue by mehlon** [zenorogue/hyperrogue#98]
The git tag for 10.5e was `v10.5e`, 11.2 was `v112`, and 11.3a was `113a`.
This makes it a bit difficult for package maintainers. For instance the [Nix package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/games/hyperrogue/default.nix#L11) has to remove the dots in the URL in order to keep the versioning consistent.
Could you go back to using the "v10.5e" template? Prepending a "v" for version releases is a good wide-spread convention, and keeping the dots in the git tag means the git tag can be generated from the version without hassle.
If you can, please re-tag the current 11.3a release as `v11.3a`.

**Comment by zenorogue** [comment]
Not sure how the inconsistency happened, but I will try to keep this convention. Thanks! Also tagged v11.3f.
